Operation =1
Option =0
Where ="(((zBsPromo.RecID) Is Null))"
Begin InputTables
    Name ="mReadPromo"
    Name ="zBsPromo"
End
Begin OutputColumns
    Expression ="mReadPromo.RecID"
    Expression ="mReadPromo.ID"
    Expression ="mReadPromo.PendingId"
    Expression ="mReadPromo.SubmittedBy"
    Expression ="mReadPromo.SubmitDt"
    Expression ="mReadPromo.SubmitOffice"
    Expression ="mReadPromo.Title"
    Expression ="mReadPromo.Tel"
    Expression ="mReadPromo.Ext"
    Expression ="mReadPromo.Fax"
    Expression ="mReadPromo.Email"
    Expression ="mReadPromo.Type"
    Expression ="mReadPromo.PromoNm"
    Expression ="mReadPromo.PromoOffer"
    Expression ="mReadPromo.OfferText"
    Expression ="mReadPromo.EffDate"
    Expression ="mReadPromo.ExpDate"
    Expression ="mReadPromo.HSImedia"
    Expression ="mReadPromo.MediaMn"
    Expression ="mReadPromo.Tier1"
    Expression ="mReadPromo.Tier2"
    Expression ="mReadPromo.Tier3"
    Expression ="mReadPromo.Tier4"
    Expression ="mReadPromo.TOC"
    Expression ="mReadPromo.TOCNm"
    Expression ="mReadPromo.STOC"
    Expression ="mReadPromo.STOCNm"
    Expression ="mReadPromo.EffMnth"
    Expression ="mReadPromo.EffQtr"
    Expression ="mReadPromo.EffYr"
    Expression ="mReadPromo.ImpQtr"
    Expression ="mReadPromo.ImpYr"
    Expression ="mReadPromo.SamplDesc"
    Expression ="mReadPromo.Lit"
    Expression ="mReadPromo.PcsRep"
    Expression ="mReadPromo.PcsCtr"
    Expression ="mReadPromo.Div"
    Expression ="mReadPromo.Dept"
    Expression ="mReadPromo.Approvd"
    Expression ="mReadPromo.ApprvBy"
    Expression ="mReadPromo.ApprvDt"
    Expression ="mReadPromo.VIPApprvBy"
    Expression ="mReadPromo.VIPApprvDt"
    Expression ="mReadPromo.VIPStatus"
    Expression ="mReadPromo.VIPType"
    Expression ="mReadPromo.DftPromo"
    Expression ="mReadPromo.DftPg"
    Expression ="mReadPromo.DftFlier"
    Expression ="mReadPromo.SaleFlyer"
    Expression ="mReadPromo.TargetGroup"
    Expression ="mReadPromo.TargetZone"
    Expression ="mReadPromo.OrderLevel"
    Expression ="mReadPromo.SWO"
    Expression ="mReadPromo.RedeemDt"
    Expression ="mReadPromo.RedeemOpt"
    Expression ="mReadPromo.RdmTel"
    Expression ="mReadPromo.RdmFax"
    Expression ="mReadPromo.FlyerNm"
    Expression ="mReadPromo.PgNo"
    Expression ="mReadPromo.FSCSells"
    Expression ="mReadPromo.FSCGets"
    Expression ="mReadPromo.HSIMinVolume"
    Expression ="mReadPromo.HSIRebate"
    Expression ="mReadPromo.BuyInOffer"
    Expression ="mReadPromo.BuyInStart"
    Expression ="mReadPromo.BuyInEnd"
    Expression ="mReadPromo.Fulfillment"
    Expression ="mReadPromo.Quantity"
    Expression ="mReadPromo.Notes"
    Expression ="mReadPromo.PromoCode"
    Expression ="mReadPromo.EZ"
    Expression ="mReadPromo.MP"
    Expression ="mReadPromo.WhoGets"
    Expression ="mReadPromo.HowSent"
    Expression ="mReadPromo.SentDate"
    Expression ="mReadPromo.DistReps"
    Expression ="mReadPromo.HSIContact"
    Expression ="mReadPromo.FlyerPg"
    Expression ="mReadPromo.FldCom"
    Expression ="mReadPromo.FldNotes"
    Expression ="mReadPromo.MgdNotes"
    Expression ="mReadPromo.StreetSuite"
    Expression ="mReadPromo.CityStZip"
    Expression ="mReadPromo.VndTel"
    Expression ="mReadPromo.VndFax"
    Expression ="mReadPromo.WebSite"
    Expression ="mReadPromo.PromoCd"
    Expression ="mReadPromo.AdMn"
    Expression ="mReadPromo.AdStart"
    Expression ="mReadPromo.AdEnd"
    Expression ="mReadPromo.AdNm"
    Expression ="mReadPromo.AdOffer"
    Expression ="mReadPromo.AdText"
    Expression ="mReadPromo.AdRdmDt"
    Expression ="mReadPromo.AdRdmOpt"
    Expression ="mReadPromo.Deletd"
    Expression ="mReadPromo.DelDt"
    Expression ="mReadPromo.DelUSER"
    Expression ="mReadPromo.SelItmSet"
    Expression ="mReadPromo.Update_Id"
    Expression ="mReadPromo.OrigRecId"
    Expression ="mReadPromo.Vendor_Id"
    Expression ="mReadPromo.Typ1"
    Expression ="mReadPromo.Typ2"
    Expression ="mReadPromo.Typ3"
    Expression ="mReadPromo.Typ4"
    Expression ="mReadPromo.Typ5"
    Expression ="mReadPromo.Typ6"
    Expression ="mReadPromo.Typ7"
    Expression ="mReadPromo.Typ8"
    Expression ="mReadPromo.Typ9"
    Expression ="mReadPromo.Typ10"
    Expression ="mReadPromo.Typ11"
    Expression ="mReadPromo.Typ12"
    Expression ="mReadPromo.RdmOpt1"
    Expression ="mReadPromo.RdmOpt2"
    Expression ="mReadPromo.RdmOpt3"
    Expression ="mReadPromo.RdmOpt4"
    Expression ="mReadPromo.RdmOpt5"
    Expression ="mReadPromo.GetValu"
    Expression ="mReadPromo.BuyCnt"
    Expression ="mReadPromo.[1inv]"
    Expression ="mReadPromo.DftNote"
    Expression ="mReadPromo.Comment"
    Expression ="mReadPromo.Same"
    Expression ="mReadPromo.BrandNmPkg"
    Expression ="mReadPromo.DelMe"
    Expression ="mReadPromo.HideMe"
    Expression ="mReadPromo.GetQty"
    Expression ="mReadPromo.GetText"
    Expression ="mReadPromo.GetType"
    Expression ="mReadPromo.SWOID"
    Expression ="mReadPromo.Limit"
End
Begin Joins
    LeftTable ="mReadPromo"
    RightTable ="zBsPromo"
    Expression ="mReadPromo.RecID = zBsPromo.RecID"
    Flag =2
End
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
Begin
End
Begin
    State =0
    Left =62
    Top =84
    Right =1568
    Bottom =396
    Left =-1
    Top =-1
    Right =1495
    Bottom =144
    Left =0
    Top =0
    ColumnsShown =539
    Begin
        Left =38
        Top =6
        Right =134
        Bottom =113
        Top =0
        Name ="mReadPromo"
        Name =""
    End
    Begin
        Left =172
        Top =6
        Right =268
        Bottom =113
        Top =0
        Name ="zBsPromo"
        Name =""
    End
End
