Operation =5
Option =0
Begin InputTables
    Name ="VipPromos"
End
Begin OutputColumns
    Expression ="VipPromos.RecID"
    Expression ="VipPromos.ID"
    Expression ="VipPromos.SubmittedBy"
    Expression ="VipPromos.SubmitDt"
    Expression ="VipPromos.SubmitOffice"
    Expression ="VipPromos.Title"
    Expression ="VipPromos.Tel"
    Expression ="VipPromos.Ext"
    Expression ="VipPromos.Fax"
    Expression ="VipPromos.Email"
    Expression ="VipPromos.Type"
    Expression ="VipPromos.PromoNm"
    Expression ="VipPromos.PromoOffer"
    Expression ="VipPromos.OfferText"
    Expression ="VipPromos.EffDate"
    Expression ="VipPromos.ExpDate"
    Expression ="VipPromos.HSImedia"
    Expression ="VipPromos.MediaMn"
    Expression ="VipPromos.Tier1"
    Expression ="VipPromos.Tier2"
    Expression ="VipPromos.Tier3"
    Expression ="VipPromos.Tier4"
    Expression ="VipPromos.TOC"
    Expression ="VipPromos.TOCNm"
    Expression ="VipPromos.STOC"
    Expression ="VipPromos.STOCNm"
    Expression ="VipPromos.EffMnth"
    Expression ="VipPromos.EffQtr"
    Expression ="VipPromos.EffYr"
    Expression ="VipPromos.ImpQtr"
    Expression ="VipPromos.ImpYr"
    Expression ="VipPromos.SamplDesc"
    Expression ="VipPromos.Lit"
    Expression ="VipPromos.PcsRep"
    Expression ="VipPromos.PcsCtr"
    Expression ="VipPromos.Div"
    Expression ="VipPromos.Dept"
    Expression ="VipPromos.Approvd"
    Expression ="VipPromos.ApprvBy"
    Expression ="VipPromos.ApprvDt"
    Expression ="VipPromos.DftPromo"
    Expression ="VipPromos.SaleFlyer"
    Expression ="VipPromos.TargetGroup"
    Expression ="VipPromos.TargetZone"
    Expression ="VipPromos.OrderLevel"
    Expression ="VipPromos.SWO"
    Expression ="VipPromos.RedeemDt"
    Expression ="VipPromos.RedeemOpt"
    Expression ="VipPromos.RdmTel"
    Expression ="VipPromos.RdmFax"
    Expression ="VipPromos.FlyerNm"
    Expression ="VipPromos.PgNo"
    Expression ="VipPromos.FSCSells"
    Expression ="VipPromos.FSCGets"
    Expression ="VipPromos.HSIMinVolume"
    Expression ="VipPromos.HSIRebate"
    Expression ="VipPromos.BuyInOffer"
    Expression ="VipPromos.BuyInStart"
    Expression ="VipPromos.BuyInEnd"
    Expression ="VipPromos.Fulfillment"
    Expression ="VipPromos.Quantity"
    Expression ="VipPromos.Notes"
    Expression ="VipPromos.PromoCode"
    Expression ="VipPromos.EZ"
    Expression ="VipPromos.MP"
    Expression ="VipPromos.WhoGets"
    Expression ="VipPromos.HowSent"
    Expression ="VipPromos.SentDate"
    Expression ="VipPromos.DistReps"
    Expression ="VipPromos.HSIContact"
    Expression ="VipPromos.FlyerPg"
    Expression ="VipPromos.FldCom"
    Expression ="VipPromos.FldNotes"
    Expression ="VipPromos.MgdNotes"
    Expression ="VipPromos.StreetSuite"
    Expression ="VipPromos.CityStZip"
    Expression ="VipPromos.VndTel"
    Expression ="VipPromos.VndFax"
    Expression ="VipPromos.WebSite"
    Expression ="VipPromos.PromoCd"
    Expression ="VipPromos.AdMn"
    Expression ="VipPromos.AdStart"
    Expression ="VipPromos.AdEnd"
    Expression ="VipPromos.AdNm"
    Expression ="VipPromos.AdOffer"
    Expression ="VipPromos.AdText"
    Expression ="VipPromos.AdRdmDt"
    Expression ="VipPromos.AdRdmOpt"
    Expression ="VipPromos.Deletd"
    Expression ="VipPromos.DelDt"
    Expression ="VipPromos.DelUSER"
    Expression ="VipPromos.SelItmSet"
End
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbBoolean "UseTransaction" ="-1"
dbBoolean "FailOnError" ="0"
dbByte "Orientation" ="0"
Begin
End
Begin
    State =0
    Left =62
    Top =84
    Right =1002
    Bottom =396
    Left =-1
    Top =-1
    Right =933
    Bottom =144
    Left =0
    Top =0
    ColumnsShown =771
    Begin
        Left =38
        Top =6
        Right =134
        Bottom =113
        Top =0
        Name ="VipPromos"
        Name =""
    End
End
