Operation =1
Option =0
Where ="(((zReadItemSub.RecID) Is Null))"
Begin InputTables
    Name ="zReadPromo"
    Name ="zReadItemSub"
End
Begin OutputColumns
    Expression ="zReadPromo.RecID"
    Expression ="zReadPromo.ID"
    Expression ="zReadPromo.PendingId"
    Expression ="zReadPromo.SubmittedBy"
    Expression ="zReadPromo.SubmitDt"
    Expression ="zReadPromo.SubmitOffice"
    Expression ="zReadPromo.Title"
    Expression ="zReadPromo.Tel"
    Expression ="zReadPromo.Ext"
    Expression ="zReadPromo.Fax"
    Expression ="zReadPromo.Email"
    Expression ="zReadPromo.Type"
    Expression ="zReadPromo.PromoNm"
    Expression ="zReadPromo.PromoOffer"
    Expression ="zReadPromo.OfferText"
    Expression ="zReadPromo.EffDate"
    Expression ="zReadPromo.ExpDate"
    Expression ="zReadPromo.HSImedia"
    Expression ="zReadPromo.MediaMn"
    Expression ="zReadPromo.Tier1"
    Expression ="zReadPromo.Tier2"
    Expression ="zReadPromo.Tier3"
    Expression ="zReadPromo.Tier4"
    Expression ="zReadPromo.TOC"
    Expression ="zReadPromo.TOCNm"
    Expression ="zReadPromo.STOC"
    Expression ="zReadPromo.STOCNm"
    Expression ="zReadPromo.EffMnth"
    Expression ="zReadPromo.EffQtr"
    Expression ="zReadPromo.EffYr"
    Expression ="zReadPromo.ImpQtr"
    Expression ="zReadPromo.ImpYr"
    Expression ="zReadPromo.SamplDesc"
    Expression ="zReadPromo.Lit"
    Expression ="zReadPromo.PcsRep"
    Expression ="zReadPromo.PcsCtr"
    Expression ="zReadPromo.Div"
    Expression ="zReadPromo.Dept"
    Expression ="zReadPromo.Approvd"
    Expression ="zReadPromo.ApprvBy"
    Expression ="zReadPromo.ApprvDt"
    Expression ="zReadPromo.VIPApprvBy"
    Expression ="zReadPromo.VIPApprvDt"
    Expression ="zReadPromo.VIPStatus"
    Expression ="zReadPromo.VIPType"
    Expression ="zReadPromo.DftPromo"
    Expression ="zReadPromo.DftPg"
    Expression ="zReadPromo.DftFlier"
    Expression ="zReadPromo.SaleFlyer"
    Expression ="zReadPromo.TargetGroup"
    Expression ="zReadPromo.TargetZone"
    Expression ="zReadPromo.OrderLevel"
    Expression ="zReadPromo.SWO"
    Expression ="zReadPromo.RedeemDt"
    Expression ="zReadPromo.RedeemOpt"
    Expression ="zReadPromo.RdmTel"
    Expression ="zReadPromo.RdmFax"
    Expression ="zReadPromo.FlyerNm"
    Expression ="zReadPromo.PgNo"
    Expression ="zReadPromo.FSCSells"
    Expression ="zReadPromo.FSCGets"
    Expression ="zReadPromo.HSIMinVolume"
    Expression ="zReadPromo.HSIRebate"
    Expression ="zReadPromo.BuyInOffer"
    Expression ="zReadPromo.BuyInStart"
    Expression ="zReadPromo.BuyInEnd"
    Expression ="zReadPromo.Fulfillment"
    Expression ="zReadPromo.Quantity"
    Expression ="zReadPromo.Notes"
    Expression ="zReadPromo.PromoCode"
    Expression ="zReadPromo.EZ"
    Expression ="zReadPromo.MP"
    Expression ="zReadPromo.WhoGets"
    Expression ="zReadPromo.HowSent"
    Expression ="zReadPromo.SentDate"
    Expression ="zReadPromo.DistReps"
    Expression ="zReadPromo.HSIContact"
    Expression ="zReadPromo.FlyerPg"
    Expression ="zReadPromo.FldCom"
    Expression ="zReadPromo.FldNotes"
    Expression ="zReadPromo.MgdNotes"
    Expression ="zReadPromo.StreetSuite"
    Expression ="zReadPromo.CityStZip"
    Expression ="zReadPromo.VndTel"
    Expression ="zReadPromo.VndFax"
    Expression ="zReadPromo.WebSite"
    Expression ="zReadPromo.PromoCd"
    Expression ="zReadPromo.AdMn"
    Expression ="zReadPromo.AdStart"
    Expression ="zReadPromo.AdEnd"
    Expression ="zReadPromo.AdNm"
    Expression ="zReadPromo.AdOffer"
    Expression ="zReadPromo.AdText"
    Expression ="zReadPromo.AdRdmDt"
    Expression ="zReadPromo.AdRdmOpt"
    Expression ="zReadPromo.Deletd"
    Expression ="zReadPromo.DelDt"
    Expression ="zReadPromo.DelUSER"
    Expression ="zReadPromo.SelItmSet"
    Expression ="zReadPromo.Update_Id"
    Expression ="zReadPromo.OrigRecId"
    Expression ="zReadPromo.Vendor_Id"
    Expression ="zReadPromo.Typ1"
    Expression ="zReadPromo.Typ2"
    Expression ="zReadPromo.Typ3"
    Expression ="zReadPromo.Typ4"
    Expression ="zReadPromo.Typ5"
    Expression ="zReadPromo.Typ6"
    Expression ="zReadPromo.Typ7"
    Expression ="zReadPromo.Typ8"
    Expression ="zReadPromo.Typ9"
    Expression ="zReadPromo.Typ10"
    Expression ="zReadPromo.Typ11"
    Expression ="zReadPromo.Typ12"
    Expression ="zReadPromo.RdmOpt1"
    Expression ="zReadPromo.RdmOpt2"
    Expression ="zReadPromo.RdmOpt3"
    Expression ="zReadPromo.RdmOpt4"
    Expression ="zReadPromo.RdmOpt5"
    Expression ="zReadPromo.GetValu"
    Expression ="zReadPromo.BuyCnt"
    Expression ="zReadPromo.[1inv]"
    Expression ="zReadPromo.DftNote"
    Expression ="zReadPromo.Comment"
    Expression ="zReadPromo.Same"
    Expression ="zReadPromo.BrandNmPkg"
    Expression ="zReadPromo.DelMe"
    Expression ="zReadPromo.HideMe"
    Expression ="zReadPromo.GetQty"
    Expression ="zReadPromo.GetText"
    Expression ="zReadPromo.GetType"
    Expression ="zReadPromo.SWOID"
End
Begin Joins
    LeftTable ="zReadPromo"
    RightTable ="zReadItemSub"
    Expression ="zReadPromo.RecID = zReadItemSub.RecID"
    Flag =2
End
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
Begin
End
Begin
    State =0
    Left =40
    Top =62
    Right =1258
    Bottom =374
    Left =-1
    Top =-1
    Right =1207
    Bottom =144
    Left =0
    Top =0
    ColumnsShown =539
    Begin
        Left =38
        Top =6
        Right =134
        Bottom =113
        Top =0
        Name ="zReadPromo"
        Name =""
    End
    Begin
        Left =172
        Top =6
        Right =268
        Bottom =113
        Top =0
        Name ="zReadItemSub"
        Name =""
    End
End
