Option Compare Database

Sub Clear()

'DoCmd.SetWarnings (WarningOff)

DoCmd.RunSQL "delete from [Alpha]"
DoCmd.RunSQL "delete from [Archive]"
DoCmd.RunSQL "delete from [BrandNmPkgPre]"
DoCmd.RunSQL "delete from [BrandNmPkgPreStruct]"
DoCmd.RunSQL "delete from [BrandPkg]"
DoCmd.RunSQL "delete from [BrandPkgStruct]"
DoCmd.RunSQL "delete from [BuyCnt]"
DoCmd.RunSQL "delete from [DefPro1z]"
DoCmd.RunSQL "delete from [DefProTest]"
DoCmd.RunSQL "delete from [DispMfg]"
DoCmd.RunSQL "delete from [DispNm]"
DoCmd.RunSQL "delete from [DispNmStruct]"
DoCmd.RunSQL "delete from [Done]"
DoCmd.RunSQL "delete from [DupsICs]"
DoCmd.RunSQL "delete from [DupzBuy]"
DoCmd.RunSQL "delete from [E3 NAME]"
DoCmd.RunSQL "delete from [E3Nm]"
DoCmd.RunSQL "delete from [E3NmPkgSz]"
DoCmd.RunSQL "delete from [E3NmPkgSzStruct]"
DoCmd.RunSQL "delete from [E3NmStruct]"
DoCmd.RunSQL "delete from [EmlLtr]"
DoCmd.RunSQL "delete from [ExcpRptSuppliersLocal]"
DoCmd.RunSQL "delete from [ExpVal]"
DoCmd.RunSQL "delete from [HSIPromoT]"
DoCmd.RunSQL "delete from [ImportLog]"
DoCmd.RunSQL "delete from [ImportTest]"
DoCmd.RunSQL "delete from [ImpVipEd]"
DoCmd.RunSQL "delete from [ImpVipEdStruct]"
DoCmd.RunSQL "delete from [ImpVipEdTbl]"
DoCmd.RunSQL "delete from [ImpVipNu]"
DoCmd.RunSQL "delete from [ImpVipNuStruct]"
DoCmd.RunSQL "delete from [ImpVipNu-X]"
DoCmd.RunSQL "delete from [Item Codes]"
DoCmd.RunSQL "delete from [ItemMasterStruct]"
DoCmd.RunSQL "delete from [LinksTable]"
DoCmd.RunSQL "delete from [LinksTable_SQL]"
DoCmd.RunSQL "delete from [MnCDefT]"
DoCmd.RunSQL "delete from [MnCItemsT]"
DoCmd.RunSQL "delete from [MnCPromoT]"
DoCmd.RunSQL "delete from [mReadBNP]"
DoCmd.RunSQL "delete from [PreIC]"
DoCmd.RunSQL "delete from [ProData]"
DoCmd.RunSQL "delete from [PromoDetailsT]"
DoCmd.RunSQL "delete from [PromoTestTbl]"
DoCmd.RunSQL "delete from [Promotion_Detail_Update]"
DoCmd.RunSQL "delete from [QtyMisMatch]"
DoCmd.RunSQL "delete from [QtyMisMatchOrig]"
DoCmd.RunSQL "delete from [QtyMisMatchStruct]"
DoCmd.RunSQL "delete from [RedeemOptionT]"
DoCmd.RunSQL "delete from [rVCnSupplier]"
DoCmd.RunSQL "delete from [rVendorList]"
DoCmd.RunSQL "delete from [rVendorListStruct]"
DoCmd.RunSQL "delete from [rVndICs]"
DoCmd.RunSQL "delete from [rVndICsStruct]"
DoCmd.RunSQL "delete from [RZsizeAVL]"
DoCmd.RunSQL "delete from [RZsizeAVLstruct]"
DoCmd.RunSQL "delete from [SrcFilesStruct]"
DoCmd.RunSQL "delete from [SrcFilesT]"
DoCmd.RunSQL "delete from [SWOInpt]"
DoCmd.RunSQL "delete from [TestSheet1]"
DoCmd.RunSQL "delete from [TmpIC]"
DoCmd.RunSQL "delete from [TmpPromo]"
DoCmd.RunSQL "delete from [vCode]"
DoCmd.RunSQL "delete from [VipItemFile]"
DoCmd.RunSQL "delete from [VipMasterItemFile]"
DoCmd.RunSQL "delete from [VipMasterItemFile-hold]"
DoCmd.RunSQL "delete from [VipMasterItemFileZ]"
DoCmd.RunSQL "delete from [VipPromoExp]"
DoCmd.RunSQL "delete from [VipPromoExpStruct]"
DoCmd.RunSQL "delete from [WCS ITEMFILE]"
DoCmd.RunSQL "delete from [WCSitemfile]"
DoCmd.RunSQL "delete from [xTOCSTOCDT]"
DoCmd.RunSQL "delete from [zBsBNP]"
DoCmd.RunSQL "delete from [zBuyDups]"
DoCmd.RunSQL "delete from [zBuyTmp]"
DoCmd.RunSQL "delete from [zBuyTmpStruct]"
DoCmd.RunSQL "delete from [zCorpNSub]"
DoCmd.RunSQL "delete from [zCorpNSubPreSend]"
DoCmd.RunSQL "delete from [zCorpNSubSend]"
DoCmd.RunSQL "delete from [zCorpNSubSendStruct]"
DoCmd.RunSQL "delete from [zCorpNSubStruct]"
DoCmd.RunSQL "delete from [zCorpNSubT]"
DoCmd.RunSQL "delete from [zCorpNSubTStruct]"
DoCmd.RunSQL "delete from [zHdrTmp]"
DoCmd.RunSQL "delete from [zHdrTmpStruct]"
DoCmd.RunSQL "delete from [zItemCompile]"
DoCmd.RunSQL "delete from [zItemCompileStruct]"
DoCmd.RunSQL "delete from [zItemDupKeepers]"
DoCmd.RunSQL "delete from [zItems2Kill]"
DoCmd.RunSQL "delete from [zItemSet]"
DoCmd.RunSQL "delete from [zItemSub1z]"
DoCmd.RunSQL "delete from [zItemSubDelT]"
DoCmd.RunSQL "delete from [zItemSubDupsT]"
DoCmd.RunSQL "delete from [zItemSubDupsTStruct]"
DoCmd.RunSQL "delete from [zItemSubKeeps]"
DoCmd.RunSQL "delete from [zItemSubNu]"
DoCmd.RunSQL "delete from [zItemZub]"
DoCmd.RunSQL "delete from [zItmFamSet]"
DoCmd.RunSQL "delete from [zItmFixT]"
DoCmd.RunSQL "delete from [zItmFixTorig]"
DoCmd.RunSQL "delete from [zItmTmp]"
DoCmd.RunSQL "delete from [zItmTmpStruct]"
DoCmd.RunSQL "delete from [zPreICStruct]"
DoCmd.RunSQL "delete from [zPromo1z]"
DoCmd.RunSQL "delete from [zPromoDupsStruct]"
DoCmd.RunSQL "delete from [zPromoDupsT]"
DoCmd.RunSQL "delete from [zPromoItemSubX]"
DoCmd.RunSQL "delete from [zPromoMtqT]"
DoCmd.RunSQL "delete from [zPromoTest]"
DoCmd.RunSQL "delete from [zPromoX]"
DoCmd.RunSQL "delete from [zTmpICStruct]"
DoCmd.RunSQL "delete from [zTmpPromoStruct]"
DoCmd.RunSQL "delete from [zTSIC]"
DoCmd.RunSQL "delete from [zVCs]"
DoCmd.RunSQL "delete from [zWCSsupplier]"
DoCmd.RunSQL "delete from [zWCSsupplierStruct]"

DoCmd.RunSQL "delete from [AllSTOCLink]"
DoCmd.RunSQL "delete from [AllTOCLink]"
DoCmd.RunSQL "delete from [ArubAmfg]"
DoCmd.RunSQL "delete from [Buy]"
DoCmd.RunSQL "delete from [CatTocItmDEN]"
DoCmd.RunSQL "delete from [CatTocItmLAB]"
DoCmd.RunSQL "delete from [dbLog]"
DoCmd.RunSQL "delete from [DispMfgNm]"
DoCmd.RunSQL "delete from [Dtl]"
DoCmd.RunSQL "delete from [ExcpRptSuppliers]"
DoCmd.RunSQL "delete from [Hdr]"
DoCmd.RunSQL "delete from [ImportOK]"
DoCmd.RunSQL "delete from [ItemBrandNamePkg]"
DoCmd.RunSQL "delete from [ItemCdWdispMfgCd]"
DoCmd.RunSQL "delete from [JDEDesc]"
DoCmd.RunSQL "delete from [JDESzeStr]"
DoCmd.RunSQL "delete from [PRICE BREAK (RETAIL)]"
DoCmd.RunSQL "delete from [Promo]"
DoCmd.RunSQL "delete from [Promotion_Buy_Update]"
DoCmd.RunSQL "delete from [Stk]"
DoCmd.RunSQL "delete from [VIPbufferBuy]"
DoCmd.RunSQL "delete from [VIPbufferBuy-V]"
DoCmd.RunSQL "delete from [VIPbufferDetail]"
DoCmd.RunSQL "delete from [VIPbufferHeader]"
DoCmd.RunSQL "delete from [VipBuy]"
DoCmd.RunSQL "delete from [VipBuyPre]"
DoCmd.RunSQL "delete from [VipItems]"
DoCmd.RunSQL "delete from [VipItemsPre]"
DoCmd.RunSQL "delete from [VipLiveVCs]"
DoCmd.RunSQL "delete from [VipMasterItemFileOKd]"
DoCmd.RunSQL "delete from [VipMasterItemFilePre]"
DoCmd.RunSQL "delete from [VipPromos]"
DoCmd.RunSQL "delete from [VipPromosPre]"
DoCmd.RunSQL "delete from [VipSubVCs]"
DoCmd.RunSQL "delete from [VipSubVCsPre]"
DoCmd.RunSQL "delete from [WcsItemFileCSV]"
DoCmd.RunSQL "delete from [WCSitemfilePre]"
DoCmd.RunSQL "delete from [zBsBuy]"
DoCmd.RunSQL "delete from [zBsItemSub]"
DoCmd.RunSQL "delete from [zBsPromo]"
DoCmd.RunSQL "delete from [zBsSubVC]"
DoCmd.RunSQL "delete from [zBsVendor]"

DoCmd.RunSQL "delete from [ExpPromo]"
DoCmd.RunSQL "delete from [SchdLog]"
DoCmd.RunSQL "delete from [zGiftCode]"

DoCmd.RunSQL "delete from [CMS_vw_BrandNamePkg]"
DoCmd.RunSQL "delete from [dbo_E3Names]"
DoCmd.RunSQL "delete from [dbo_ItemMfrDisplay]"
DoCmd.RunSQL "delete from [dbo_NPFIMS]"



End Sub